export const links = [
  {
    id: "1",
    originalUrl:
      "https://example.com/very-long-path/blog/article-with-a-very-long-name-123",
    shortUrl: "linksy.com/r/product",
    createdAt: "2023-10-15T14:23:11Z",
    clicks: 856,
    isActive: true,
  },
  {
    id: "2",
    originalUrl: "https://another-example.com/path/to/resource",
    shortUrl: "linksy.com/r/webinar",
    createdAt: "2023-10-12T09:45:22Z",
    clicks: 532,
    isActive: true,
  },
  {
    id: "3",
    originalUrl:
      "https://long-domain-name-for-testing.com/another/long/path/to/test/truncation",
    shortUrl: "linksy.com/r/event",
    createdAt: "2023-10-10T16:12:09Z",
    clicks: 321,
    isActive: true,
  },
  {
    id: "4",
    originalUrl: "https://docs.example.com/getting-started",
    shortUrl: "linksy.com/r/docs",
    createdAt: "2023-10-08T11:34:55Z",
    clicks: 267,
    isActive: true,
  },
  {
    id: "5",
    originalUrl: "https://example.com/pricing",
    shortUrl: "linksy.com/r/pricing",
    createdAt: "2023-10-05T08:22:37Z",
    clicks: 198,
    isActive: true,
  },
  {
    id: "6",
    originalUrl: "https://tutorialhub.io/react/useeffect-complete-guide",
    shortUrl: "linksy.com/r/useeffect",
    createdAt: "2023-10-03T10:00:00Z",
    clicks: 189,
    isActive: true,
  },
  {
    id: "7",
    originalUrl: "https://shop.example-store.com/products/wireless-headphones",
    shortUrl: "linksy.com/r/headphones",
    createdAt: "2023-10-01T14:45:00Z",
    clicks: 134,
    isActive: true,
  },
  {
    id: "8",
    originalUrl: "https://careers.examplecorp.com/jobs/frontend-developer",
    shortUrl: "linksy.com/r/frontend",
    createdAt: "2023-09-29T09:12:34Z",
    clicks: 203,
    isActive: true,
  },
  {
    id: "9",
    originalUrl: "https://conference.techsummit2023.org/sessions/keynote",
    shortUrl: "linksy.com/r/keynote",
    createdAt: "2023-09-26T17:33:45Z",
    clicks: 412,
    isActive: true,
  },
  {
    id: "10",
    originalUrl: "https://blog.devzone.io/2023/09/nextjs-routing-tips",
    shortUrl: "linksy.com/r/nextjs-tips",
    createdAt: "2023-09-24T08:10:11Z",
    clicks: 176,
    isActive: true,
  },
  {
    id: "11",
    originalUrl: "https://helpcenter.example.com/article/account-security",
    shortUrl: "linksy.com/r/security",
    createdAt: "2023-09-22T13:55:00Z",
    clicks: 122,
    isActive: true,
  },
  {
    id: "12",
    originalUrl: "https://medium.com/@user/building-a-saas-with-nextjs",
    shortUrl: "linksy.com/r/saas-guide",
    createdAt: "2023-09-20T15:30:00Z",
    clicks: 341,
    isActive: true,
  },
  {
    id: "13",
    originalUrl: "https://openai.com/blog/chatgpt-plugins",
    shortUrl: "linksy.com/r/plugins",
    createdAt: "2023-09-18T11:15:45Z",
    clicks: 611,
    isActive: true,
  },
  {
    id: "14",
    originalUrl: "https://youtube.com/watch?v=dQw4w9WgXcQ",
    shortUrl: "linksy.com/r/surprise",
    createdAt: "2023-09-15T08:30:00Z",
    clicks: 999,
    isActive: true,
  },
  {
    id: "15",
    originalUrl: "https://designpatterns.dev/clean-code-principles",
    shortUrl: "linksy.com/r/cleancode",
    createdAt: "2023-09-12T10:10:10Z",
    clicks: 280,
    isActive: true,
  },
  {
    id: "16",
    originalUrl: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API",
    shortUrl: "linksy.com/r/fetchapi",
    createdAt: "2023-09-10T09:00:00Z",
    clicks: 143,
    isActive: true,
  },
  {
    id: "17",
    originalUrl: "https://react.dev/learn/conditional-rendering",
    shortUrl: "linksy.com/r/react-conditions",
    createdAt: "2023-09-08T16:45:00Z",
    clicks: 199,
    isActive: true,
  },
  {
    id: "18",
    originalUrl: "https://github.com/vercel/next.js/issues/12345",
    shortUrl: "linksy.com/r/next-issue",
    createdAt: "2023-09-06T14:20:00Z",
    clicks: 89,
    isActive: true,
  },
  {
    id: "19",
    originalUrl: "https://ui.shadcn.dev/components/button",
    shortUrl: "linksy.com/r/ui-button",
    createdAt: "2023-09-04T12:00:00Z",
    clicks: 305,
    isActive: true,
  },
  {
    id: "20",
    originalUrl: "https://tailwindcss.com/docs/flex",
    shortUrl: "linksy.com/r/flex-docs",
    createdAt: "2023-09-01T07:45:00Z",
    clicks: 268,
    isActive: true,
  },
];
